// beacon2/backend/src/seed/defaultRoles.js
// Default roles seeded when a new u3a tenant is created.
// Each role lists its default privileges as { code, action } pairs.
// These match the defaults shown in the Beacon documentation.

export const DEFAULT_ROLES = [
  {
    name: 'Administration',
    isCommittee: false,
    notes: 'Full administrative access. Assigned to the Site Administrator.',
    defaultPrivileges: [
      // Users & Roles
      { code: 'users_list',              action: 'view' },
      { code: 'user_record',             action: 'view' },
      { code: 'user_record',             action: 'create' },
      { code: 'user_record',             action: 'change' },
      { code: 'user_record',             action: 'delete' },
      { code: 'roles_list',              action: 'view' },
      { code: 'role_record',             action: 'view' },
      { code: 'role_record',             action: 'create' },
      { code: 'role_record',             action: 'change' },
      { code: 'role_record',             action: 'delete' },
      // Members
      { code: 'members_list',            action: 'view' },
      { code: 'members_list',            action: 'download' },
      { code: 'member_record',           action: 'view' },
      { code: 'member_record',           action: 'create' },
      { code: 'member_record',           action: 'change' },
      { code: 'member_record',           action: 'delete' },
      { code: 'member_classes',          action: 'view' },
      { code: 'member_classes',          action: 'create' },
      { code: 'member_classes',          action: 'change' },
      { code: 'member_classes',          action: 'delete' },
      { code: 'member_statuses',         action: 'view' },
      { code: 'member_statuses',         action: 'create' },
      { code: 'member_statuses',         action: 'change' },
      { code: 'member_statuses',         action: 'delete' },
      { code: 'membership_renewals',     action: 'view' },
      { code: 'membership_renewals',     action: 'renew' },
      { code: 'membership_statistics',   action: 'view' },
      { code: 'membership_statistics',   action: 'download' },
      { code: 'membership_cards',        action: 'view' },
      { code: 'membership_cards',        action: 'download_and_mark' },
      { code: 'members_recent',          action: 'view' },
      { code: 'members_recent',          action: 'download' },
      { code: 'members_non_renewals',    action: 'view' },
      { code: 'members_non_renewals',    action: 'lapse' },
      { code: 'members_delete_expired',  action: 'view' },
      { code: 'members_delete_expired',  action: 'delete' },
      // Groups
      { code: 'groups_list',             action: 'view' },
      { code: 'groups_list',             action: 'download' },
      { code: 'group_records_all',       action: 'view' },
      { code: 'group_records_all',       action: 'create' },
      { code: 'group_records_all',       action: 'change' },
      { code: 'group_records_all',       action: 'delete' },
      { code: 'group_records_all',       action: 'download_members' },
      { code: 'group_venues',            action: 'view' },
      { code: 'group_venues',            action: 'create' },
      { code: 'group_venues',            action: 'change' },
      { code: 'group_venues',            action: 'delete' },
      { code: 'group_leaders',           action: 'view' },
      { code: 'group_faculties',         action: 'view' },
      { code: 'group_faculties',         action: 'create' },
      { code: 'group_faculties',         action: 'change' },
      { code: 'group_faculties',         action: 'delete' },
      // Email
      { code: 'email',                   action: 'view' },
      { code: 'email',                   action: 'send' },
      { code: 'email_standard_messages', action: 'view' },
      { code: 'email_standard_messages', action: 'create' },
      { code: 'email_standard_messages', action: 'change' },
      { code: 'email_standard_messages', action: 'delete' },
      { code: 'email_delivery',          action: 'view' },
      // Settings & misc
      { code: 'settings',                action: 'view' },
      { code: 'settings',                action: 'change' },
      { code: 'system_messages',         action: 'view' },
      { code: 'system_messages',         action: 'create' },
      { code: 'system_messages',         action: 'change' },
      { code: 'audit_trail',             action: 'view' },
      { code: 'audit_detail',            action: 'view' },
      { code: 'data_export_backup',      action: 'view' },
      { code: 'data_export_backup',      action: 'download' },
      { code: 'offices',                 action: 'view' },
      { code: 'offices',                 action: 'create' },
      { code: 'offices',                 action: 'change' },
      { code: 'offices',                 action: 'delete' },
      { code: 'public_links',            action: 'view' },
      { code: 'calendar',                action: 'view' },
      { code: 'meetings',                action: 'view' },
      { code: 'meetings',                action: 'create' },
      { code: 'meetings',                action: 'change' },
      { code: 'meetings',                action: 'delete' },
    ],
  },

  {
    name: 'Group Leaders',
    isCommittee: false,
    notes: 'Access scoped to groups the user leads.',
    defaultPrivileges: [
      { code: 'group_records_as_leader',   action: 'view' },
      { code: 'group_records_as_leader',   action: 'change' },
      { code: 'group_records_as_leader',   action: 'delete' },
      { code: 'group_records_as_leader',   action: 'download_members' },
      { code: 'group_ledger_as_leader',    action: 'view' },
      { code: 'group_ledger_as_leader',    action: 'create' },
      { code: 'group_ledger_as_leader',    action: 'change' },
      { code: 'group_ledger_as_leader',    action: 'delete' },
      { code: 'groups_add_by_name_leader', action: 'change' },
      { code: 'groups_add_by_no_leader',   action: 'change' },
      { code: 'groups_list',               action: 'view' },
      { code: 'meetings',                  action: 'view' },
      { code: 'meetings',                  action: 'create' },
    ],
  },

  {
    name: 'Groups Coordinator',
    isCommittee: false,
    notes: 'Coordinates across all groups.',
    defaultPrivileges: [
      { code: 'groups_list',           action: 'view' },
      { code: 'groups_list',           action: 'download' },
      { code: 'group_records_all',     action: 'view' },
      { code: 'group_records_all',     action: 'create' },
      { code: 'group_records_all',     action: 'change' },
      { code: 'group_records_all',     action: 'delete' },
      { code: 'group_venues',          action: 'view' },
      { code: 'group_venues',          action: 'create' },
      { code: 'group_venues',          action: 'change' },
      { code: 'group_venues',          action: 'delete' },
      { code: 'group_leaders',         action: 'view' },
      { code: 'group_faculties',       action: 'view' },
      { code: 'group_faculties',       action: 'create' },
      { code: 'group_faculties',       action: 'change' },
      { code: 'group_faculties',       action: 'delete' },
      { code: 'groups_add_by_name',    action: 'change' },
      { code: 'groups_add_by_no',      action: 'change' },
      { code: 'meetings',              action: 'view' },
      { code: 'meetings',              action: 'create' },
    ],
  },

  {
    name: 'Membership Secretary',
    isCommittee: true,
    notes: 'Manages member records, renewals and communications.',
    defaultPrivileges: [
      { code: 'members_list',            action: 'view' },
      { code: 'members_list',            action: 'download' },
      { code: 'member_record',           action: 'view' },
      { code: 'member_record',           action: 'create' },
      { code: 'member_record',           action: 'change' },
      { code: 'member_classes',          action: 'view' },
      { code: 'member_statuses',         action: 'view' },
      { code: 'membership_renewals',     action: 'view' },
      { code: 'membership_renewals',     action: 'renew' },
      { code: 'membership_statistics',   action: 'view' },
      { code: 'membership_statistics',   action: 'download' },
      { code: 'membership_cards',        action: 'view' },
      { code: 'membership_cards',        action: 'download_and_mark' },
      { code: 'members_recent',          action: 'view' },
      { code: 'members_recent',          action: 'download' },
      { code: 'members_non_renewals',    action: 'view' },
      { code: 'members_non_renewals',    action: 'lapse' },
      { code: 'members_delete_expired',  action: 'view' },
      { code: 'members_delete_expired',  action: 'delete' },
      { code: 'address_labels',          action: 'view' },
      { code: 'address_labels',          action: 'download' },
      { code: 'addresses_export',        action: 'view' },
      { code: 'addresses_export',        action: 'download' },
      { code: 'email',                   action: 'view' },
      { code: 'email',                   action: 'send' },
      { code: 'gift_aid_declaration',    action: 'view' },
      { code: 'gift_aid_declaration',    action: 'download_and_mark' },
    ],
  },

  {
    name: 'Treasurer',
    isCommittee: true,
    notes: 'Manages financial records and accounts.',
    defaultPrivileges: [
      { code: 'finance_accounts',        action: 'view' },
      { code: 'finance_accounts',        action: 'create' },
      { code: 'finance_accounts',        action: 'change' },
      { code: 'finance_accounts',        action: 'delete' },
      { code: 'finance_batches',         action: 'view' },
      { code: 'finance_batches',         action: 'create' },
      { code: 'finance_batches',         action: 'delete' },
      { code: 'finance_categories',      action: 'view' },
      { code: 'finance_categories',      action: 'create' },
      { code: 'finance_categories',      action: 'change' },
      { code: 'finance_categories',      action: 'delete' },
      { code: 'finance_ledger',          action: 'view' },
      { code: 'finance_ledger',          action: 'download' },
      { code: 'finance_reconcile',       action: 'view' },
      { code: 'finance_reconcile',       action: 'reconcile' },
      { code: 'finance_statement',       action: 'view' },
      { code: 'finance_statement',       action: 'download' },
      { code: 'finance_transactions',    action: 'view' },
      { code: 'finance_transactions',    action: 'create' },
      { code: 'finance_transactions',    action: 'change' },
      { code: 'finance_transactions',    action: 'delete' },
      { code: 'finance_transfer_money',  action: 'view' },
      { code: 'finance_transfer_money',  action: 'create' },
      { code: 'finance_transfer_money',  action: 'change' },
      { code: 'finance_transfer_money',  action: 'delete' },
      { code: 'gift_aid_declaration',    action: 'view' },
      { code: 'gift_aid_declaration',    action: 'download_and_mark' },
      { code: 'members_list',            action: 'view' },
      { code: 'group_ledger_all',        action: 'view' },
      { code: 'group_ledger_all',        action: 'download' },
      { code: 'group_statement',         action: 'view' },
      { code: 'group_statement',         action: 'download' },
    ],
  },
];
